name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    uses: brig-id/.github/.github/workflows/ci-rust.yml@26e9a0393cb98cdb4f25e4d10f155230fb4db6f5
