name: Coverage

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  coverage:
    uses: brig-id/.github/.github/workflows/coverage.yml@main
    with:
      codecov-flags: crypto
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
