name: Coverage

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  coverage:
    uses: brig-id/.github/.github/workflows/coverage.yml@26e9a0393cb98cdb4f25e4d10f155230fb4db6f5
    with:
      codecov-flags: crypto
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
