name: Security Audit

on:
  push:
    branches: [main, dev]
  schedule:
    - cron: "0 6 * * 1" # Every Monday at 06:00 UTC

jobs:
  security:
    uses: brig-id/.github/.github/workflows/security-audit.yml@26e9a0393cb98cdb4f25e4d10f155230fb4db6f5
